#############################################################################
# Makefile for building: boggle.app/Contents/MacOS/boggle
# Generated by qmake (2.01a) (Qt 4.4.3) on: Sat Nov 29 23:49:50 2008
# Project:  boggle.pro
# Template: app
# Command: /Developer/qt/bin/qmake -macx -config release -o Makefile boggle.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -Os -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -Os -Wall -W $(DEFINES)
INCPATH       = -I/Developer/qt/mkspecs/macx-g++ -I. -I/Developer/qt/lib/QtCore.framework/Versions/4/Headers -I/Developer/qt/include/QtCore -I/Developer/qt/include/QtCore -I/Developer/qt/lib/QtGui.framework/Versions/4/Headers -I/Developer/qt/include/QtGui -I/Developer/qt/include/QtGui -I/Developer/qt/include -I. -I. -F/Developer/qt/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Developer/qt/lib -L/Developer/qt/lib -framework QtGui -L/Developer/qt/lib -F/Developer/qt/lib -framework Carbon -framework AppKit -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Developer/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sources/main.cpp \
		sources/mainwindow.cpp \
		sources/die.cpp \
		sources/dicetray.cpp \
		sources/lexicon.cpp moc_mainwindow.cpp \
		qrc_files.cpp
OBJECTS       = main.o \
		mainwindow.o \
		die.o \
		dicetray.o \
		lexicon.o \
		moc_mainwindow.o \
		qrc_files.o
DIST          = /Developer/qt/mkspecs/common/unix.conf \
		/Developer/qt/mkspecs/common/mac.conf \
		/Developer/qt/mkspecs/common/mac-g++.conf \
		/Developer/qt/mkspecs/qconfig.pri \
		/Developer/qt/mkspecs/features/qt_functions.prf \
		/Developer/qt/mkspecs/features/qt_config.prf \
		/Developer/qt/mkspecs/features/exclusive_builds.prf \
		/Developer/qt/mkspecs/features/default_pre.prf \
		/Developer/qt/mkspecs/features/mac/default_pre.prf \
		/Developer/qt/mkspecs/features/release.prf \
		/Developer/qt/mkspecs/features/default_post.prf \
		/Developer/qt/mkspecs/features/mac/default_post.prf \
		/Developer/qt/mkspecs/features/mac/objective_c.prf \
		/Developer/qt/mkspecs/features/warn_on.prf \
		/Developer/qt/mkspecs/features/qt.prf \
		/Developer/qt/mkspecs/features/unix/thread.prf \
		/Developer/qt/mkspecs/features/moc.prf \
		/Developer/qt/mkspecs/features/mac/rez.prf \
		/Developer/qt/mkspecs/features/mac/sdk.prf \
		/Developer/qt/mkspecs/features/resources.prf \
		/Developer/qt/mkspecs/features/uic.prf \
		/Developer/qt/mkspecs/features/yacc.prf \
		/Developer/qt/mkspecs/features/lex.prf \
		boggle.pro
QMAKE_TARGET  = boggle
DESTDIR       = 
TARGET        = boggle.app/Contents/MacOS/boggle

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-Os \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile boggle.app/Contents/PkgInfo boggle.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) boggle.app/Contents/MacOS/ || $(MKDIR) boggle.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: boggle.pro  /Developer/qt/mkspecs/macx-g++/qmake.conf /Developer/qt/mkspecs/common/unix.conf \
		/Developer/qt/mkspecs/common/mac.conf \
		/Developer/qt/mkspecs/common/mac-g++.conf \
		/Developer/qt/mkspecs/qconfig.pri \
		/Developer/qt/mkspecs/features/qt_functions.prf \
		/Developer/qt/mkspecs/features/qt_config.prf \
		/Developer/qt/mkspecs/features/exclusive_builds.prf \
		/Developer/qt/mkspecs/features/default_pre.prf \
		/Developer/qt/mkspecs/features/mac/default_pre.prf \
		/Developer/qt/mkspecs/features/release.prf \
		/Developer/qt/mkspecs/features/default_post.prf \
		/Developer/qt/mkspecs/features/mac/default_post.prf \
		/Developer/qt/mkspecs/features/mac/objective_c.prf \
		/Developer/qt/mkspecs/features/warn_on.prf \
		/Developer/qt/mkspecs/features/qt.prf \
		/Developer/qt/mkspecs/features/unix/thread.prf \
		/Developer/qt/mkspecs/features/moc.prf \
		/Developer/qt/mkspecs/features/mac/rez.prf \
		/Developer/qt/mkspecs/features/mac/sdk.prf \
		/Developer/qt/mkspecs/features/resources.prf \
		/Developer/qt/mkspecs/features/uic.prf \
		/Developer/qt/mkspecs/features/yacc.prf \
		/Developer/qt/mkspecs/features/lex.prf \
		/Developer/qt/lib/QtGui.framework/QtGui.prl \
		/Developer/qt/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -macx -config release -o Makefile boggle.pro
/Developer/qt/mkspecs/common/unix.conf:
/Developer/qt/mkspecs/common/mac.conf:
/Developer/qt/mkspecs/common/mac-g++.conf:
/Developer/qt/mkspecs/qconfig.pri:
/Developer/qt/mkspecs/features/qt_functions.prf:
/Developer/qt/mkspecs/features/qt_config.prf:
/Developer/qt/mkspecs/features/exclusive_builds.prf:
/Developer/qt/mkspecs/features/default_pre.prf:
/Developer/qt/mkspecs/features/mac/default_pre.prf:
/Developer/qt/mkspecs/features/release.prf:
/Developer/qt/mkspecs/features/default_post.prf:
/Developer/qt/mkspecs/features/mac/default_post.prf:
/Developer/qt/mkspecs/features/mac/objective_c.prf:
/Developer/qt/mkspecs/features/warn_on.prf:
/Developer/qt/mkspecs/features/qt.prf:
/Developer/qt/mkspecs/features/unix/thread.prf:
/Developer/qt/mkspecs/features/moc.prf:
/Developer/qt/mkspecs/features/mac/rez.prf:
/Developer/qt/mkspecs/features/mac/sdk.prf:
/Developer/qt/mkspecs/features/resources.prf:
/Developer/qt/mkspecs/features/uic.prf:
/Developer/qt/mkspecs/features/yacc.prf:
/Developer/qt/mkspecs/features/lex.prf:
/Developer/qt/lib/QtGui.framework/QtGui.prl:
/Developer/qt/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -macx -config release -o Makefile boggle.pro

boggle.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) boggle.app/Contents || $(MKDIR) boggle.app/Contents 
	@$(DEL_FILE) boggle.app/Contents/PkgInfo
	@echo "APPL????" >boggle.app/Contents/PkgInfo
boggle.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) boggle.app/Contents || $(MKDIR) boggle.app/Contents 
	@$(DEL_FILE) boggle.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,boggle,g" -e "s,@TYPEINFO@,????,g" /Developer/qt/mkspecs/macx-g++/Info.plist.app >boggle.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/boggle1.0.0 || $(MKDIR) .tmp/boggle1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/boggle1.0.0/ && $(COPY_FILE) --parents sources/mainwindow.h sources/die.h sources/dicetray.h sources/lexicon.h .tmp/boggle1.0.0/ && $(COPY_FILE) --parents resources/files.qrc .tmp/boggle1.0.0/ && $(COPY_FILE) --parents sources/main.cpp sources/mainwindow.cpp sources/die.cpp sources/dicetray.cpp sources/lexicon.cpp .tmp/boggle1.0.0/ && $(COPY_FILE) --parents sources/mainwindow.ui .tmp/boggle1.0.0/ && $(COPY_FILE) --parents translations/de.ts .tmp/boggle1.0.0/ && (cd `dirname .tmp/boggle1.0.0` && $(TAR) boggle1.0.0.tar boggle1.0.0 && $(COMPRESS) boggle1.0.0.tar) && $(MOVE) `dirname .tmp/boggle1.0.0`/boggle1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/boggle1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r boggle.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: sources/dicetray.h \
		sources/die.h \
		sources/lexicon.h \
		sources/mainwindow.h
	/Developer/qt/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ sources/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_files.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_files.cpp
qrc_files.cpp: resources/files.qrc \
		resources/dictionary.txt
	/Developer/qt/bin/rcc -name files resources/files.qrc -o qrc_files.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: sources/mainwindow.ui
	/Developer/qt/bin/uic sources/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: sources/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o sources/main.cpp

mainwindow.o: sources/mainwindow.cpp sources/mainwindow.h \
		sources/dicetray.h \
		sources/die.h \
		sources/lexicon.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o sources/mainwindow.cpp

die.o: sources/die.cpp sources/die.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o die.o sources/die.cpp

dicetray.o: sources/dicetray.cpp sources/dicetray.h \
		sources/die.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dicetray.o sources/dicetray.cpp

lexicon.o: sources/lexicon.cpp sources/lexicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lexicon.o sources/lexicon.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_files.o: qrc_files.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_files.o qrc_files.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

